<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class ClassesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $classes = [
            [
                'code' => 'FM1A',
                'name' => 'BSBA Financial Management 1A',
                'hasBreak' => 'false',
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'FM1B',
                'name' => 'BSBA Financial Management 1B',
                'hasBreak' => 'false',
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'MM1A',
                'name' => 'BSBA Marketing Management 1A',
                'hasBreak' => 'false',
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'MM1B',
                'name' => 'BSBA Marketing Management 1B',
                'hasBreak' => 'false',
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'FM2A',
                'name' => 'BSBA Financial Management 2A',
                'hasBreak' => 'false',
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'FM2B',
                'name' => 'BSBA Financial Management 2B',
                'hasBreak' => 'false',
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'FM2C',
                'name' => 'BSBA Financial Management 2C',
                'hasBreak' => 'false',
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'MM2A',
                'name' => 'BSBA Marketing Management 2A',
                'hasBreak' => 'false',
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'FM3A',
                'name' => 'BSBA Financial Management 3A',
                'hasBreak' => 'false',
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'FM3B',
                'name' => 'BSBA Financial Management 3B',
                'hasBreak' => 'false',
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'MM3A',
                'name' => 'BSBA Marketing Management 3A',
                'hasBreak' => 'false',
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'FM4A',
                'name' => 'BSBA Financial Management 4A',
                'hasBreak' => 'false',
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'FM4B',
                'name' => 'BSBA Financial Management 4B',
                'hasBreak' => 'false',
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'MM4A',
                'name' => 'BSBA Marketing Management 4A',
                'hasBreak' => 'false',
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'BSCS1A',
                'name' => 'BSCS1A',
                'hasBreak' => 'false',
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'BSCS1B',
                'name' => 'BSCS1B',
                'hasBreak' => 'false',
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'BSCS2A',
                'name' => 'BSCS2A',
                'hasBreak' => 'false',
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'BSCS2B',
                'name' => 'BSCS2B',
                'hasBreak' => 'false',
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'BSCS3A',
                'name' => 'BSCS3A',
                'hasBreak' => 'false',
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'BSCS4A',
                'name' => 'BSCS4A',
                'hasBreak' => 'false',
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'BSCS4B',
                'name' => 'BSCS4B',
                'hasBreak' => 'false',
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'BSEENG1A',
                'name' => 'BSE English 1A',
                'hasBreak' => 'false',
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'BSEENG2A',
                'name' => 'BSE English 2A',
                'hasBreak' => 'false',
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'BSEENG3A',
                'name' => 'BSE English 3A',
                'hasBreak' => 'false',
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'BSEENG4A',
                'name' => 'BSE English 4A',
                'hasBreak' => 'false',
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'BSEFIL1A',
                'name' => 'BSE Filipino 1A',
                'hasBreak' => 'false',
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'BSEFIL1B',
                'name' => 'BSE Filipino 1B',
                'hasBreak' => 'false',
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'BSEFIL2A',
                'name' => 'BSE Filipino 2A',
                'hasBreak' => 'false',
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'BSEFIL2B',
                'name' => 'BSE Filipino 2B',
                'hasBreak' => 'false',
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'BSEFIL3A',
                'name' => 'BSE Filipino 3A',
                'hasBreak' => 'false',
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'BSEFIL3B',
                'name' => 'BSE Filipino 3B',
                'hasBreak' => 'false',
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'BSEFIL4A',
                'name' => 'BSE Filipino 4A',
                'hasBreak' => 'false',
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'BSEMATH1A',
                'name' => 'BSE Math 1A',
                'hasBreak' => 'false',
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'BSEMATH2A',
                'name' => 'BSE Math 2A',
                'hasBreak' => 'false',
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'BSEMATH3A',
                'name' => 'BSE Math 3A',
                'hasBreak' => 'false',
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'BSEMATH4A',
                'name' => 'BSE Math 4A',
                'hasBreak' => 'false',
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'BSESS1A',
                'name' => 'BSE Social Studies 1A',
                'hasBreak' => 'false',
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'BSESS1B',
                'name' => 'BSE Social Studies 1B',
                'hasBreak' => 'false',
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'BSESS2A',
                'name' => 'BSE Social Studies 2A',
                'hasBreak' => 'false',
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'BSESS2B',
                'name' => 'BSE Social Studies 2B',
                'hasBreak' => 'false',
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'BSESS3A',
                'name' => 'BSE Social Studies 3A',
                'hasBreak' => 'false',
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'BSESS4A',
                'name' => 'BSE Social Studies 4A',
                'hasBreak' => 'false',
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'DG7A',
                'name' => 'Grade 7A (DHS)',
                'hasBreak' => true,
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'DG7B',
                'name' => 'Grade 7B (DHS)',
                'hasBreak' => true,
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'DG8A',
                'name' => 'Grade 8A (DHS)',
                'hasBreak' => true,
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'DG8B',
                'name' => 'Grade 8B (DHS)',
                'hasBreak' => true,
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'DG9A',
                'name' => 'Grade 9A (DHS)',
                'hasBreak' => true,
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'DG9B',
                'name' => 'Grade 9B (DHS)',
                'hasBreak' => true,
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'DG10A',
                'name' => 'Grade 10A (DHS)',
                'hasBreak' => true,
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'DG10B',
                'name' => 'Grade 10B (DHS)',
                'hasBreak' => true,
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'DG10C',
                'name' => 'Grade 10C (DHS)',
                'hasBreak' => true,
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'NG7A',
                'name' => 'Grade 7A (NHS)',
                'hasBreak' => 'false',
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'NG8A',
                'name' => 'Grade 8A (NHS)',
                'hasBreak' => 'false',
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'NG9A',
                'name' => 'Grade 9A (NHS)',
                'hasBreak' => 'false',
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'NG10A',
                'name' => 'Grade 10A (NHS)',
                'hasBreak' => 'false',
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'GAS11A',
                'name' => 'GAS 11A',
                'hasBreak' => true,
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'GAS11B',
                'name' => 'GAS 11B',
                'hasBreak' => true,
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'ABM11',
                'name' => 'ABM 11',
                'hasBreak' => true,
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'STEM11',
                'name' => 'STEM 11',
                'hasBreak' => true,
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'HUMSS11',
                'name' => 'HUMSS 11',
                'hasBreak' => true,
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'TVL11',
                'name' => 'TVL 11',
                'hasBreak' => true,
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'GAS12',
                'name' => 'GAS 12',
                'hasBreak' => true,
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'ABM12',
                'name' => 'ABM 12',
                'hasBreak' => true,
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'STEM12',
                'name' => 'STEM 12',
                'hasBreak' => true,
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'HUMSS12A',
                'name' => 'HUMSS 12A',
                'hasBreak' => true,
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'HUMSS12B',
                'name' => 'HUMSS 12B',
                'hasBreak' => true,
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
            [
                'code' => 'TVL12A',
                'name' => 'TVL 12A',
                'hasBreak' => true,
                'startTime' => '12:00 PM',
                'endTime' => '1:00 PM',
            ],
        ];

        foreach ($classes as $class) {
            DB::table('sections')->insert($class);
        }
    }
}
